// flow-typed signature: eaacc54791a7b017957f045bd2512158
// flow-typed version: <<STUB>>/jasmine-expect-jsx_v^1.1.7/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-expect-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-expect-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-expect-jsx/dist/jasmine-expect-jsx' {
  declare module.exports: any;
}

declare module 'jasmine-expect-jsx/spec/index.test' {
  declare module.exports: any;
}

declare module 'jasmine-expect-jsx/spec/support/jestSetup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-expect-jsx/dist/jasmine-expect-jsx.js' {
  declare module.exports: $Exports<'jasmine-expect-jsx/dist/jasmine-expect-jsx'>;
}
declare module 'jasmine-expect-jsx/index' {
  declare module.exports: $Exports<'jasmine-expect-jsx'>;
}
declare module 'jasmine-expect-jsx/index.js' {
  declare module.exports: $Exports<'jasmine-expect-jsx'>;
}
declare module 'jasmine-expect-jsx/spec/index.test.js' {
  declare module.exports: $Exports<'jasmine-expect-jsx/spec/index.test'>;
}
declare module 'jasmine-expect-jsx/spec/support/jestSetup.js' {
  declare module.exports: $Exports<'jasmine-expect-jsx/spec/support/jestSetup'>;
}
