// flow-typed signature: e7fa2e4453e7754c83aebfa42a7074c8
// flow-typed version: <<STUB>>/jasmine-expect_v^3.7.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-expect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-expect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-expect/dist/jasmine-matchers' {
  declare module.exports: any;
}

declare module 'jasmine-expect/dist/jasmine-matchers.spec' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/index' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/lib/every' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/lib/is' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/lib/keys' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/lib/memberMatcherFor' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/lib/reduce' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeAfter' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeArray' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeArrayOfBooleans' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeArrayOfNumbers' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeArrayOfObjects' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeArrayOfSize' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeArrayOfStrings' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeBefore' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeBoolean' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeCalculable' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeDate' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeEmptyArray' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeEmptyObject' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeEmptyString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeEvenNumber' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeFalse' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeFunction' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeGreaterThanOrEqualTo' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeHtmlString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeIso8601' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeJsonString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeLessThanOrEqualTo' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeLongerThan' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeNear' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeNonEmptyArray' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeNonEmptyObject' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeNonEmptyString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeNumber' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeObject' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeOddNumber' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeRegExp' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeSameLengthAs' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeShorterThan' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeTrue' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeValidDate' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeWhitespace' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeWholeNumber' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toBeWithinRange' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toEndWith' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveArray' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveArrayOfBooleans' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveArrayOfNumbers' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveArrayOfObjects' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveArrayOfSize' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveArrayOfStrings' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveBoolean' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveCalculable' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveDate' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveDateAfter' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveDateBefore' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveEmptyArray' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveEmptyObject' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveEmptyString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveEvenNumber' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveFalse' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveHtmlString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveIso8601' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveJsonString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveMember' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveMethod' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveNonEmptyArray' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveNonEmptyObject' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveNonEmptyString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveNumber' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveNumberWithinRange' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveObject' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveOddNumber' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveStringLongerThan' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveStringSameLengthAs' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveStringShorterThan' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveTrue' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveUndefined' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveWhitespaceString' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toHaveWholeNumber' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toStartWith' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toThrowAnyError' {
  declare module.exports: any;
}

declare module 'jasmine-expect/src/toThrowErrorOfType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-expect/dist/jasmine-matchers.js' {
  declare module.exports: $Exports<'jasmine-expect/dist/jasmine-matchers'>;
}
declare module 'jasmine-expect/dist/jasmine-matchers.spec.js' {
  declare module.exports: $Exports<'jasmine-expect/dist/jasmine-matchers.spec'>;
}
declare module 'jasmine-expect/index' {
  declare module.exports: $Exports<'jasmine-expect'>;
}
declare module 'jasmine-expect/index.js' {
  declare module.exports: $Exports<'jasmine-expect'>;
}
declare module 'jasmine-expect/src/index.js' {
  declare module.exports: $Exports<'jasmine-expect/src/index'>;
}
declare module 'jasmine-expect/src/lib/every.js' {
  declare module.exports: $Exports<'jasmine-expect/src/lib/every'>;
}
declare module 'jasmine-expect/src/lib/is.js' {
  declare module.exports: $Exports<'jasmine-expect/src/lib/is'>;
}
declare module 'jasmine-expect/src/lib/keys.js' {
  declare module.exports: $Exports<'jasmine-expect/src/lib/keys'>;
}
declare module 'jasmine-expect/src/lib/memberMatcherFor.js' {
  declare module.exports: $Exports<'jasmine-expect/src/lib/memberMatcherFor'>;
}
declare module 'jasmine-expect/src/lib/reduce.js' {
  declare module.exports: $Exports<'jasmine-expect/src/lib/reduce'>;
}
declare module 'jasmine-expect/src/toBeAfter.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeAfter'>;
}
declare module 'jasmine-expect/src/toBeArray.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeArray'>;
}
declare module 'jasmine-expect/src/toBeArrayOfBooleans.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeArrayOfBooleans'>;
}
declare module 'jasmine-expect/src/toBeArrayOfNumbers.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeArrayOfNumbers'>;
}
declare module 'jasmine-expect/src/toBeArrayOfObjects.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeArrayOfObjects'>;
}
declare module 'jasmine-expect/src/toBeArrayOfSize.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeArrayOfSize'>;
}
declare module 'jasmine-expect/src/toBeArrayOfStrings.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeArrayOfStrings'>;
}
declare module 'jasmine-expect/src/toBeBefore.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeBefore'>;
}
declare module 'jasmine-expect/src/toBeBoolean.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeBoolean'>;
}
declare module 'jasmine-expect/src/toBeCalculable.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeCalculable'>;
}
declare module 'jasmine-expect/src/toBeDate.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeDate'>;
}
declare module 'jasmine-expect/src/toBeEmptyArray.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeEmptyArray'>;
}
declare module 'jasmine-expect/src/toBeEmptyObject.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeEmptyObject'>;
}
declare module 'jasmine-expect/src/toBeEmptyString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeEmptyString'>;
}
declare module 'jasmine-expect/src/toBeEvenNumber.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeEvenNumber'>;
}
declare module 'jasmine-expect/src/toBeFalse.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeFalse'>;
}
declare module 'jasmine-expect/src/toBeFunction.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeFunction'>;
}
declare module 'jasmine-expect/src/toBeGreaterThanOrEqualTo.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeGreaterThanOrEqualTo'>;
}
declare module 'jasmine-expect/src/toBeHtmlString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeHtmlString'>;
}
declare module 'jasmine-expect/src/toBeIso8601.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeIso8601'>;
}
declare module 'jasmine-expect/src/toBeJsonString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeJsonString'>;
}
declare module 'jasmine-expect/src/toBeLessThanOrEqualTo.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeLessThanOrEqualTo'>;
}
declare module 'jasmine-expect/src/toBeLongerThan.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeLongerThan'>;
}
declare module 'jasmine-expect/src/toBeNear.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeNear'>;
}
declare module 'jasmine-expect/src/toBeNonEmptyArray.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeNonEmptyArray'>;
}
declare module 'jasmine-expect/src/toBeNonEmptyObject.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeNonEmptyObject'>;
}
declare module 'jasmine-expect/src/toBeNonEmptyString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeNonEmptyString'>;
}
declare module 'jasmine-expect/src/toBeNumber.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeNumber'>;
}
declare module 'jasmine-expect/src/toBeObject.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeObject'>;
}
declare module 'jasmine-expect/src/toBeOddNumber.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeOddNumber'>;
}
declare module 'jasmine-expect/src/toBeRegExp.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeRegExp'>;
}
declare module 'jasmine-expect/src/toBeSameLengthAs.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeSameLengthAs'>;
}
declare module 'jasmine-expect/src/toBeShorterThan.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeShorterThan'>;
}
declare module 'jasmine-expect/src/toBeString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeString'>;
}
declare module 'jasmine-expect/src/toBeTrue.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeTrue'>;
}
declare module 'jasmine-expect/src/toBeValidDate.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeValidDate'>;
}
declare module 'jasmine-expect/src/toBeWhitespace.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeWhitespace'>;
}
declare module 'jasmine-expect/src/toBeWholeNumber.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeWholeNumber'>;
}
declare module 'jasmine-expect/src/toBeWithinRange.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toBeWithinRange'>;
}
declare module 'jasmine-expect/src/toEndWith.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toEndWith'>;
}
declare module 'jasmine-expect/src/toHaveArray.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveArray'>;
}
declare module 'jasmine-expect/src/toHaveArrayOfBooleans.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveArrayOfBooleans'>;
}
declare module 'jasmine-expect/src/toHaveArrayOfNumbers.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveArrayOfNumbers'>;
}
declare module 'jasmine-expect/src/toHaveArrayOfObjects.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveArrayOfObjects'>;
}
declare module 'jasmine-expect/src/toHaveArrayOfSize.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveArrayOfSize'>;
}
declare module 'jasmine-expect/src/toHaveArrayOfStrings.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveArrayOfStrings'>;
}
declare module 'jasmine-expect/src/toHaveBoolean.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveBoolean'>;
}
declare module 'jasmine-expect/src/toHaveCalculable.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveCalculable'>;
}
declare module 'jasmine-expect/src/toHaveDate.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveDate'>;
}
declare module 'jasmine-expect/src/toHaveDateAfter.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveDateAfter'>;
}
declare module 'jasmine-expect/src/toHaveDateBefore.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveDateBefore'>;
}
declare module 'jasmine-expect/src/toHaveEmptyArray.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveEmptyArray'>;
}
declare module 'jasmine-expect/src/toHaveEmptyObject.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveEmptyObject'>;
}
declare module 'jasmine-expect/src/toHaveEmptyString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveEmptyString'>;
}
declare module 'jasmine-expect/src/toHaveEvenNumber.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveEvenNumber'>;
}
declare module 'jasmine-expect/src/toHaveFalse.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveFalse'>;
}
declare module 'jasmine-expect/src/toHaveHtmlString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveHtmlString'>;
}
declare module 'jasmine-expect/src/toHaveIso8601.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveIso8601'>;
}
declare module 'jasmine-expect/src/toHaveJsonString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveJsonString'>;
}
declare module 'jasmine-expect/src/toHaveMember.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveMember'>;
}
declare module 'jasmine-expect/src/toHaveMethod.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveMethod'>;
}
declare module 'jasmine-expect/src/toHaveNonEmptyArray.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveNonEmptyArray'>;
}
declare module 'jasmine-expect/src/toHaveNonEmptyObject.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveNonEmptyObject'>;
}
declare module 'jasmine-expect/src/toHaveNonEmptyString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveNonEmptyString'>;
}
declare module 'jasmine-expect/src/toHaveNumber.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveNumber'>;
}
declare module 'jasmine-expect/src/toHaveNumberWithinRange.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveNumberWithinRange'>;
}
declare module 'jasmine-expect/src/toHaveObject.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveObject'>;
}
declare module 'jasmine-expect/src/toHaveOddNumber.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveOddNumber'>;
}
declare module 'jasmine-expect/src/toHaveString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveString'>;
}
declare module 'jasmine-expect/src/toHaveStringLongerThan.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveStringLongerThan'>;
}
declare module 'jasmine-expect/src/toHaveStringSameLengthAs.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveStringSameLengthAs'>;
}
declare module 'jasmine-expect/src/toHaveStringShorterThan.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveStringShorterThan'>;
}
declare module 'jasmine-expect/src/toHaveTrue.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveTrue'>;
}
declare module 'jasmine-expect/src/toHaveUndefined.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveUndefined'>;
}
declare module 'jasmine-expect/src/toHaveWhitespaceString.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveWhitespaceString'>;
}
declare module 'jasmine-expect/src/toHaveWholeNumber.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toHaveWholeNumber'>;
}
declare module 'jasmine-expect/src/toStartWith.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toStartWith'>;
}
declare module 'jasmine-expect/src/toThrowAnyError.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toThrowAnyError'>;
}
declare module 'jasmine-expect/src/toThrowErrorOfType.js' {
  declare module.exports: $Exports<'jasmine-expect/src/toThrowErrorOfType'>;
}
