// flow-typed signature: ed2f7c39694acb84bac8f72cf805ca2d
// flow-typed version: <<STUB>>/jasmine-collection-matchers_v^0.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-collection-matchers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-collection-matchers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-collection-matchers/Gruntfile' {
  declare module.exports: any;
}

declare module 'jasmine-collection-matchers/src/toHaveLength' {
  declare module.exports: any;
}

declare module 'jasmine-collection-matchers/src/toHaveSameItems' {
  declare module.exports: any;
}

declare module 'jasmine-collection-matchers/src/toHaveUniqueItems' {
  declare module.exports: any;
}

declare module 'jasmine-collection-matchers/util/jasmineRevertSpecs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-collection-matchers/Gruntfile.js' {
  declare module.exports: $Exports<'jasmine-collection-matchers/Gruntfile'>;
}
declare module 'jasmine-collection-matchers/index' {
  declare module.exports: $Exports<'jasmine-collection-matchers'>;
}
declare module 'jasmine-collection-matchers/index.js' {
  declare module.exports: $Exports<'jasmine-collection-matchers'>;
}
declare module 'jasmine-collection-matchers/src/toHaveLength.js' {
  declare module.exports: $Exports<'jasmine-collection-matchers/src/toHaveLength'>;
}
declare module 'jasmine-collection-matchers/src/toHaveSameItems.js' {
  declare module.exports: $Exports<'jasmine-collection-matchers/src/toHaveSameItems'>;
}
declare module 'jasmine-collection-matchers/src/toHaveUniqueItems.js' {
  declare module.exports: $Exports<'jasmine-collection-matchers/src/toHaveUniqueItems'>;
}
declare module 'jasmine-collection-matchers/util/jasmineRevertSpecs.js' {
  declare module.exports: $Exports<'jasmine-collection-matchers/util/jasmineRevertSpecs'>;
}
